### ISSUE TITLE
WebHook

### ISSUE THREAD

**Issue by MasterGroosha** [vizigin/petrovich#2]
Не могли бы Вы пояснить, хотя бы вкратце, как работает WebHook и в каком виде ему приходят данные? (сейчас использую GetUpdates)

**Comment by vizigin** [comment]
Вообще webhooks пришёл ещё от [Slack](https://api.slack.com/outgoing-webhooks). API Telegram непрерывно шлёт HTTP запросы на url, который вы задаёте только один раз в методе [setWebhook](https://core.telegram.org/bots/api#setwebhook).

В документации написано, что в данный момент api шлёт на 4 разных порта: 443, 80, 88, 8443 (до воскресенья 28 июня слали только на 443 и ничего не работало :)). Heroku собирает эти запросы и посылает на 5000 порт. У меня на этом порту работает скрипт, который слушает порт и забирает все полученые пакеты.

Приходит обычный объект типа [Message](https://core.telegram.org/bots/api#message)

**Comment by MasterGroosha** [comment]
Предположим, у меня есть свой сервер. Бот написан на Python. Мне необходимо поставить вебхук на ip.моего.сервера:какой-то_порт, а в боте поставить прослушивание этого порта?

**Comment by vizigin** [comment]
Да. Всё верно

**Comment by MasterGroosha** [comment]
Спасибо за разъяснение!
